# Generated by Django 3.1.7 on 2021-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0002_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
